CONFIG_ZMK_SLEEP=n
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
CONFIG_BT_PERIPHERAL_PREF_LATENCY=30
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400
CONFIG_BT_MAX_CONN=2
CONFIG_BT_MAX_PAIRED=5
CONFIG_ZMK_SPLIT_BLE_CENTRAL_POSITION_QUEUE_SIZE=20
CONFIG_ZMK_SPLIT_BLE_CENTRAL_SPLIT_RUN_STACK_SIZE=2048
CONFIG_ZMK_SPLIT_BLE_CENTRAL_SPLIT_RUN_QUEUE_SIZE=20
CONFIG_ZMK_SPLIT_BLE_PERIPHERAL_STACK_SIZE=2048
CONFIG_ZMK_SPLIT_BLE_PERIPHERAL_PRIORITY=5
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_BT_BUF_ACL_TX_SIZE=251
CONFIG_BT_L2CAP_TX_MTU=251
CONFIG_BT_L2CAP_TX_BUF_COUNT=8
CONFIG_BT_CTLR_SDC_MAX_CONN_EVENT_LEN_DEFAULT=7500
CONFIG_ZMK_IDLE_TIMEOUT=900000
CONFIG_ZMK_USB_LOGGING=n
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_BEHAVIOR_TAP_DANCE=y
CONFIG_ZMK_BEHAVIOR_HOLD_TAP=y